image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

jobLint:
  stage: lint
  script:
   - npm run lint

jobTest:
  stage: test
  script:
   - npm run test

jobCoverage:
  stage: coverage
  script:
    - npm run coverage

steps:
  - lint
  - test
  - coverage